spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nexo_db}
    username: ${DB_USERNAME:franco}
    password: ${DB_PASSWORD:asdqwe123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "format_sql": true
    open-in-view: false
security:
  default:
    role: USER
  jwt:
    secret-key: jJ4Gs6z0vWZlJMQW6QzK6AzyvSvhk1C2H1Xt1b+bh9GqB0HnEwNfX1pWxW4W2PjN
    expiration-in-minutes: 30
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1